const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const time=n=>`${Math.floor(n/3600)} ч ${String(Math.floor(n%3600/60)).padStart(2,'0')} м`;
const bridge=window.blaze;
const paths={note:'M6 3h9l5 5v13H6z M15 3v6h5 M9 13h8 M9 17h6',route:'M5 5h11a4 4 0 0 1 0 8H9a4 4 0 0 0 0 8h7 M5 2a3 3 0 1 0 0 6a3 3 0 0 0 0-6 M19 18a3 3 0 1 0 0 6a3 3 0 0 0 0-6',focus:'M12 3a9 9 0 1 0 0 18a9 9 0 0 0 0-18 M12 7v5l4 2',days:'M4 6h16v15H4z M8 3v5 M16 3v5 M4 11h16 M8 15h2 M14 15h2',activity:'M3 3v18h18 M7 16v-5 M12 16V7 M17 16V4',health:'M12 21 3 12a5 5 0 0 1 9-7a5 5 0 0 1 9 7z',monitor:'M3 4h18v14H3z M12 18v4 M8 22h8'};
const icon=t=>`<svg viewBox="0 0 24 26" aria-hidden="true"><path d="${paths[t]||paths.activity}"/></svg>`;
let data,focus={duration:1500,remaining:1500,running:false};
function renderPin(){const b=document.querySelector('#pin'),label=data.pin?'Открепить от других окон':'Закрепить поверх окон';b.setAttribute('aria-pressed',String(data.pin));b.setAttribute('aria-label',label);b.title=label;b.innerHTML='<svg viewBox="0 0 24 24"><path d="m9 3 9 9-4 1-3 5-5-5 5-3ZM6 18l-3 3"/></svg>';}
function renderFocus(){const label=document.querySelector('[data-timer]'),ring=document.querySelector('.progress');if(label)label.textContent=`${String(Math.floor(focus.remaining/60)).padStart(2,'0')}:${String(focus.remaining%60).padStart(2,'0')}`;if(ring)ring.style.strokeDashoffset=402*(1-Math.min(1,focus.remaining/focus.duration));document.querySelector('[data-command=start]')?.setAttribute('aria-label',focus.paused?'Продолжить фокус':'Начать фокус');}
function render(w){if(!w)return;data=w;document.body.className=w.type;document.querySelector('#title').textContent=w.type==='note'?'Быстрая заметка':w.type==='focus'?'Время фокус':w.type==='days'?'Рабочие дни':['apps','activity'].includes(w.type)?'Активность':w.title;document.querySelector('#type-icon').innerHTML=icon(w.type);document.querySelector('#open').textContent=w.type==='note'?'···':'↗';
const theme=window.BlazeColors.theme(w.color);document.body.style.setProperty('--accent',theme.background);document.body.style.setProperty('--note-border',theme.border);document.body.style.background=w.type==='note'?theme.background:'#16191a';document.body.style.color=w.type==='note'?theme.text:'#f2f4ee';renderPin();const body=document.querySelector('#body');
if(w.type==='note')body.innerHTML=`<h1>${esc(w.headline)}</h1>${w.body?`<p>${esc(w.body)}</p>`:''}<div class="tasks">${(w.tasks||[]).map((t,i)=>`<label><input type="checkbox" data-index="${i}" ${t.done?'checked':''}><span>${esc(t.text)}</span></label>`).join('')}</div><div class="note-footer"><span>Сохранено в Blaze</span><button data-action="pin" aria-label="Закрепить или открепить виджет">${icon('monitor')}</button></div>`;
else if(w.type==='route')body.innerHTML=`<div class="route-map"><svg viewBox="0 0 470 170" preserveAspectRatio="none" style="width:100%;height:100%;stroke:none"><rect width="470" height="170" fill="#2b3125"/><path d="M360 0q-80 90 90 170" stroke="#35483c" stroke-width="40"/><path d="M0 40Q190 10 470 54M0 92Q210 62 470 110M0 148Q230 118 470 160M50 0l50 170M150 0l48 170M260 0l44 170M360 0l50 170" fill="none" stroke="#414938" stroke-width="7"/><path d="m90 137 70-14-16-62 170 10 26 51" fill="none" stroke="${theme.background}" stroke-width="5"/><circle cx="90" cy="137" r="7" fill="#11170f" stroke="${theme.background}" stroke-width="5"/><circle cx="340" cy="122" r="13" fill="#11170f" stroke="${theme.background}" stroke-width="2"/><circle cx="340" cy="122" r="5" fill="${theme.background}"/></svg><span class="route-badge">Маршрут</span></div><div class="route-info"><div><div class="addresses"><span title="${esc(w.route?.from)}">${esc(w.route?.from||'Дом')}</span><b>→</b><span title="${esc(w.route?.to)}">${esc(w.route?.to||'Офис')}</span></div><div class="muted">${({mt:'Общественный транспорт',auto:'На машине',pd:'Пешком'})[w.route?.mode]||'Общественный транспорт'}</div></div><button class="primary" data-action="route">${icon('route')}Построить</button></div><div class="desktop-status">На рабочем столе</div>`;
else if(w.type==='focus'){body.innerHTML='<div class="timer"><svg viewBox="0 0 150 150"><circle class="track" cx="75" cy="75" r="64"/><circle class="progress" cx="75" cy="75" r="64"/></svg><div class="timer-label"><strong data-timer></strong><small>до перерыва</small></div></div><div class="timer-controls"><button data-command="pause" aria-label="Пауза">Ⅱ</button><button data-command="add" aria-label="Добавить пять минут">+</button><button data-command="start" aria-label="Начать фокус">▸</button></div>';renderFocus();}
else if(w.type==='days'){const count=(w.workDays||[]).filter(d=>d.startsWith(day().slice(0,7))).length,goal=Math.max(1,Math.min(31,w.goal||22));body.innerHTML=`<div class="days-total"><strong>${count}</strong><span>дней работы</span><small>цель: ${goal} дня</small></div><div class="day-grid" style="grid-template-columns:repeat(${Math.ceil(goal/2)},1fr)">${Array.from({length:goal},(_,i)=>`<span class="${i<count?'done':''}" aria-label="${i<count?'Отработано':'Осталось'}">${i<count?'✓':''}</span>`).join('')}</div><button class="primary" data-action="days"><b>＋</b>Отметить день</button>`;}
else if(['apps','activity'].includes(w.type)){const rows=Object.entries(w.activity?.[day()]||{}).sort((a,b)=>b[1]-a[1]),total=rows.reduce((n,r)=>n+r[1],0),max=rows[0]?.[1]||1;body.innerHTML=`<div class="activity-total">${time(total)}</div><div class="app-grid">${rows.length?rows.slice(0,6).map(([name,seconds],i)=>`<div class="app-row"><span class="app-symbol" style="color:${['#b399fb','#80bce9','#ced4c4'][i%3]}">${esc(name[0])}</span><div class="app-detail"><div class="app-label"><span>${esc(name)}</span><small>${time(seconds)}</small></div><div class="app-bar"><i style="width:${seconds/max*100}%;background:${['#b399fb','#80bce9','#ced4c4'][i%3]}"></i></div></div></div>`).join(''):'<span class="empty">Здесь появится время в программах.</span>'}</div>`;}
else body.innerHTML=`<h1>Каждые ${w.interval} мин</h1><p>${esc(w.body)}</p>`;
}
async function pin(){if(!data||!bridge)return;const b=document.querySelector('#pin');b.disabled=true;try{data.pin=await bridge.setWidgetPinned(!data.pin);renderPin();}catch{document.querySelector('#error').textContent='Не удалось изменить закрепление';}finally{b.disabled=false;}}
document.querySelector('#pin').onclick=pin;document.querySelector('#close').onclick=()=>bridge?.windowControl('close');document.querySelector('#open').onclick=()=>bridge?.widgetAction(data.type==='note'?'edit':data.type==='route'?'route':'activity');
document.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.action==='pin')return pin();if(button.dataset.action)bridge?.widgetAction(button.dataset.action);if(button.dataset.command&&bridge){try{focus=await bridge.focusCommand(button.dataset.command);renderFocus();}catch{document.querySelector('#error').textContent='Не удалось изменить таймер';}}});
document.addEventListener('change',e=>{if(e.target.dataset.index!==undefined&&data){data.tasks[Number(e.target.dataset.index)].done=e.target.checked;bridge?.changeWidget({tasks:data.tasks});}});
if(bridge){bridge.onWidget(render);bridge.getWidget().then(render);bridge.onFocus(s=>{focus=s;renderFocus();});bridge.getFocus().then(s=>{if(s){focus=s;renderFocus();}});}


